---
# tasks file for apache

- name: install httpd
  ansible.builtin.yum:
    name: httpd
    state: present

- name: copy the index file
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html

- name: start httpd service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: reconfigure apache to run on port 8080
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
   - restart httpd service 
  
